// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uatxrhkbslqnfazzodyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhdHhyaGtic2xxbmZhenpvZHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjUwODcsImV4cCI6MjA2NDU0MTA4N30.RvrbYmZ5bew9lDFyjFolswBk-TxN-YMdm8hbdy6ugZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);